### ISSUE TITLE
Errors installing on win7

### ISSUE THREAD

**Issue by brupelo** [nicholasbishop/pyglsl_parser#1]
Hi, I'd like to give it a shot to your library, I'm using win7+py3.5.1_x64 and it's failing when trying to install it using either pip or easy_install.

Could you advice here?

Btw, are you still maintaining this one?

**Comment by nicholasbishop** [comment]
That's not too surprising, I never tested it on Windows. Can you paste the full error you are seeing?

**Comment by brupelo** [comment]
I see, please find below the full errors:

 - When doing `>pip install pyglsl_parser` , [here](https://gist.github.com/brupelo/b793cc27cd70c1a6298bbabacc882ea1)
 - When doing `>easy_install pyglsl_parser`, [here](https://gist.github.com/brupelo/3f33c690967a43a078b4594b590b52a8)

As you can see, both of them are pretty much the same linker errors. Tried the commands from a vs2015 x86 cmd prompt

**Comment by nicholasbishop** [comment]
Should be fixed now. I don't have a good understanding of why MSVC needs the `delete` definitions for these particular specializations, nor do I really get why `glsl-parser` decided to use a placement `new` style of memory management, but adding empty definitions makes it build (still with lots of warnings) and the tests pass.

I set up appveyor CI with a badge on the readme, so hopefully we can catch any such problems in the future.

**Comment by brupelo** [comment]
@nicholasbishop Awesome, thanks for your effort! I'd really like to give it a shot to this one. After trying with py3.5.1 & py3.5.2 I've realized it was using the old broken cached package `pyglsl_parser-0.6.1.tar.gz`. 

So, how do you recommend I should install this one? Maybe I should wait till you update [pypi](https://pypi.python.org/pypi/pyglsl_parser/)?

**Comment by nicholasbishop** [comment]
Good call, I forgot to push the new version to pypi. Should be fixed now.

**Comment by brupelo** [comment]
Great! 0.6.2 installed smoothly on both 3.5.1 & 3.5.2 now ;-D . Last question, where would you recommend me to start reading from to get a feeling from all the features available on the package?

**Comment by nicholasbishop** [comment]
Unfortunately there's not much in the way of documentation available. It pretty much just parses GLSL into an abstract syntax tree, so you can get a reasonable overview by looking at the [example.py](https://github.com/nicholasbishop/pyglsl_parser/blob/master/example.py). I realize that's not a very good answer though, so please let me know if you run into any particular difficulties.
